server:
  port: 9090
ws:
  location: http://localhost:8080/ws
  security:
    password:
      policy: classpath:passwordSecurityPolicy.xml
    certificate:
      policy: classpath:certificateSecurityPolicy.xml
      trustStore: classpath:trustStore.jks
      password: changeit
      alias: thinktech
logging:
  level:
    org.springframework.ws: TRACE
